version: '3'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - default_app-network

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "85:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - HOSTNAME=app.test
        networks:
            - default_app-network
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - '3309:3306'
        volumes:
            - .data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'root'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - default_app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=0
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=root
        restart: unless-stopped
        ports:
            - "8082:80"
        volumes:
            - /sessions
        networks:
            - default_app-network
networks:
    default_app-network:
        driver: bridge
